apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kafka-template
objects:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: operator-group
    namespace: csb-example-avro
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: strimzi-kafka-operator
    namespace: csb-example-avro
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: strimzi-kafka-operator
    source: community-operators
    sourceNamespace: openshift-marketplace
    startingCSV: ${STARTING_CSV}
- apiVersion: kafka.strimzi.io/v1beta2
  kind: Kafka
  metadata:
    name: my-cluster
    namespace: csb-example-avro
  spec:
    kafka:
      config:
        default.replication.factor: 1
        inter.broker.protocol.version: "3.4"
        min.insync.replicas: 1
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      replicas: 1
      storage:
        type: ephemeral
      version: 3.4.0
    zookeeper:
      replicas: 1
      storage:
        type: ephemeral
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaTopic
  metadata:
    labels:
      strimzi.io/cluster: my-cluster
    name: employees
    namespace: csb-example-avro
  spec:
    partitions: 10
    replicas: 1
parameters:
- description: Starting CSV for strimzi-kafka-operator
  name: STARTING_CSV
