== Resilience4j Example

=== Introduction

This example shows how to use Camel with Resilience4j EIP as circuit breaker
in Camel routes

The example includes three sub maven modules that implement

* client
* service1
* service2

Where client -> service1 client -> service2 (fallback)

=== Build

You will need to compile this example first:

[source,sh]
----
$ mvn compile
----

=== Run the example

Then using three different shells and run service1 and service2 before
the client.

[source,sh]
----
$ cd service1
$ mvn spring-boot:run
----

When service1 is ready then start service2

[source,sh]
----
$ cd service2
$ mvn spring-boot:run
----

And then start the client that calls service1 every second.

[source,sh]
----
$ cd client
$ mvn spring-boot:run
----

You can then stop service1 and see that the client should fallback to
call service2 in the Resilience EIP circuit breaker. And then start service
1 again and see the Resilience EIP go back to normal.


=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/support.html[let us know].

We also love contributors, so
https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!
